---
- name: BACKUP ALL CONFIGS
  hosts: allvendors # a group of groups containing many vendors
  gather_facts: false
  connection: network_cli


  tasks:

    - name: RETRIEVE CONFIGURATION
      cli_command:
        command: "{{backup}}"
      register: backup
      become: yes

    - name: MOVE TO FILE
      copy:
        content: "{{backup.stdout}}"
        dest: "{{inventory_hostname}}.backup"
