---
- name: A playbook to launch openstack VM
  hosts: localhost

  vars:
    vmtocreate: "vm-bloom-east2"

  tasks:
  - os_flavor_info:
      cloud: alta3cloud
    register: flavresult

  - debug:
      msg: "{{ flavresult.openstack_flavors[0].name }}"

  - name: Gather information about a previously created image named image1
    os_image_info:
      cloud: alta3cloud   
    register: imgresult

  - name: Show openstack information
    debug:
      msg: "{{ imgresult.openstack_image[0].name }}"

  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       cloud: alta3cloud       
       name: "{{ vmtocreate }}"
       image: "{{ imgresult.openstack_image[0].name }}"
       timeout: 300
       flavor: "{{ flavresult.openstack_flavors[0].name }}"
       meta:
         purpose: "backup web service"
